
#include <Servo.h>
// Defining Servo pins
Servo s1,s2,s4,s5,s6; 
int ipos1,ipos2,ipos3,ipos4,ipos5,ipos6;
int pos=0,ipos=0,data;
void setup() {
  pinMode(10,OUTPUT);
  s1.attach(2);//claw
  s2.attach(3);//plam
  s4.attach(5);//elbow
  s5.attach(6);//shoulder
  s6.attach(7);//base
  Serial.begin(9600);
}
void loop() {
 if (Serial.available()>0)  
  { 
    data=Serial.read(); 
    delay(1000);
    //go to the object location and prepare to pick
      for(pos=90;pos>=0;pos--)
     {
      s6.write(pos);
      delay(5);
     }
     delay(1000);
     for(pos=90;pos>=50;pos--)
     {
      s5.write(pos);
      delay(10);
     }
     delay(1000);
     for(pos=90;pos<=110;pos++)
     {
      s4.write(pos);
      delay(10);
     }
     delay(1000);
     for(pos=90;pos<=180;pos++)
     {
      s1.write(pos);
      delay(10);
     }
     delay(1000);
     for(pos=90;pos>=40;pos--)
     {
      s2.write(pos);
      delay(10);
     }
     delay(1000);
    //take object from its location
     for(pos=180;pos>=0;pos--)
     {
      s1.write(pos);
      delay(10);
     }
     delay(1000);
     for(pos=40;pos<=100;pos++)
     {
      s2.write(pos);
      delay(10);
     }
     delay(1000);
     for(pos=45;pos<=90;pos++)
     {
      s5.write(pos);
      delay(10);
     }  
     delay(1000);

   switch(data)
   {
    case 'A' :
   {
    //to place object(small blue) to their respective places
     for(pos=0;pos<=180;pos++)
     {
      s6.write(pos);
      delay(5);
      ipos6=pos;
     }
     delay(1000);
     for(pos=100;pos>=50;pos--)
     {
      s2.write(pos);
      delay(10);
      ipos2=pos;
     }
     delay(1000);
     for(pos=90;pos>=60;pos--)
     {
      s4.write(pos);
      delay(10);
      ipos4=pos;
     }
     delay(1000);
     for(pos=90;pos>=45;pos--)
     { 
      s5.write(pos);
      delay(10);
      ipos5=pos;
     }
     delay(1000);
     for(pos=0;pos<=180;pos++)
     {
      s1.write(pos);
      delay(10);
      ipos1=pos;
     }
     delay(1000);
     //to go to initial position which is 90 degree(IDEAL position for all 180 degree servos)
   for(ipos=ipos2;ipos<=150;ipos++)
    {
      s2.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos1;ipos>=90;ipos--)
     {
      s1.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos4;ipos<=90;ipos++)
     {
      s4.write(ipos);
      delay(5);
     }
     delay(1000);
     for(ipos=ipos5;ipos<=90;ipos++)
     {
      s5.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=ipos6;ipos>=90;ipos--)
     {
      s6.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=150;ipos>=90;ipos--)
     {
      s2.write(ipos);
      delay(10);
    }
   }
   break;
    case 'B':
    {
      //to place object(small red) to their respective places
      for(pos=0;pos<=165;pos++)
     {
      s6.write(pos);
      delay(5);
      ipos6=pos;
     }
     delay(1000);
     for(pos=100;pos>=50;pos--)
     {
      s2.write(pos);
      delay(10);
      ipos2=pos;
     }
     delay(1000);
     for(pos=90;pos>=60;pos--)
     {
      s4.write(pos);
      delay(10);
      ipos4=pos;
     }
     for(pos=90;pos>=45;pos--)
     { 
      s5.write(pos);
      delay(10);
      ipos5=pos;
     }
     delay(1000);
     for(pos=0;pos<=180;pos++)
     {
      s1.write(pos);
      delay(10);
      ipos1=pos;
     }
    delay(1000);
    //to go to initial position which is 90 degree(IDEAL position for all 180 degree servos)
   for(ipos=ipos2;ipos<=150;ipos++)
    {
      s2.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos1;ipos>=90;ipos--)
     {
      s1.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos4;ipos<=90;ipos++)
     {
      s4.write(ipos);
      delay(5);
     }
     delay(1000);
     for(ipos=ipos5;ipos<=90;ipos++)
     {
      s5.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=ipos6;ipos>=90;ipos--)
     {
      s6.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=150;ipos>=90;ipos--)
     {
      s2.write(ipos);
      delay(10);
    }
    }
    break;
  
  case 'C' :
    {
      //to place object(big blue) to their respective places
      for(pos=0;pos<=180;pos++)
     {
      s6.write(pos);
      delay(5);
      ipos6=pos;
     }
     delay(1000);
     for(pos=100;pos>=0;pos--)
     {
      s2.write(pos);
      delay(10);
      ipos2=pos;
     }
     delay(1000);
     for(pos=0;pos<=180;pos++)
     {
      s1.write(pos);
      delay(10);
      ipos1=pos;
     }
     //to go to initial position which is 90 degree(IDEAL position for all 180 degree servos)
   for(ipos=ipos2;ipos<=150;ipos++)
    {
      s2.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos1;ipos>=90;ipos--)
     {
      s1.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos6;ipos>=90;ipos--)
     {
      s6.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=150;ipos>=90;ipos--)
     {
      s2.write(ipos);
      delay(10);
    }
     delay(1000);
    }
    
    break;
   case 'D' :
    {
      //to place object(big blue) to their respective places
      for(pos=0;pos<=155;pos++)
     {
      s6.write(pos);
      delay(5);
      ipos6=pos;
     }
     delay(1000);
     for(pos=100;pos>=0;pos--)
     {
      s2.write(pos);
      delay(10);
      ipos2=pos;
     }
     delay(1000);
     for(pos=0;pos<=180;pos++)
     {
      s1.write(pos);
      delay(10);
      ipos1=pos;
     }
     delay(1000);
    //to go to initial position which is 90 degree(IDEAL position for all 180 degree servos)
   for(ipos=ipos2;ipos<=150;ipos++)
    {
      s2.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos1;ipos>=90;ipos--)
     {
      s1.write(ipos);
      delay(10);
    }
    delay(1000);
    for(ipos=ipos6;ipos>=90;ipos--)
     {
      s6.write(ipos);
      delay(5);
     }
    delay(1000);
    for(ipos=150;ipos>=90;ipos--)
     {
      s2.write(ipos);
      delay(10);
    }
   }
   break;
 }
}
}
